baseURL = "https://fnikolai.github.io/frisbee-www"
languageCode = "en-us"
theme = "frisbee"

contentDir = "content"
publishdir = "public"
enableEmoji = true


canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]



[build]
useResourceCacheWhen="never"

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.highlight]
style = "manni"
guessSyntax = true


[Permalinks]
code = "/:filename/"


[params]
title = "Helm"
description = "Frisbee: Smart, Cloud-Native Testbed!"

ghrepo = "https://github.com/CARV-ICS-FORTH/frisbee"

website = "https://fnikolai.github.io/frisbee-www"

docsrepo = "https://github.com/CARV-ICS-FORTH/frisbee/tree/main/docs"

forum = "https://github.com/CARV-ICS-FORTH/frisbee/discussions"


#googleAnalyticsId = "UA-42867143-2"
#googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
#twittersite = "helmpack"
#twittertype = "summary"
#twitterimage = "img/og-image.png"

jsFiles = [
  "foundation",
  "foundation.accordion",
  "foundation.dropdown",
  "foundation.offcanvas",
  "foundation.slider",
  "foundation.tooltip",
  "modernizr",
  "clipboard.min",
  "app"
]


# Multilingual configuration
defaultContentLanguage = "en"
disableLanguages = ["el"]

# English
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 1



