[[docs]]
  name = "About Frisbee"
  weight = 1
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "Getting Started"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started"
  post = "break"


# Core Menus


[[docs]]
  name = "User's Guide"
  weight = 20
  identifier = "users-guide"
  url = "/users-guide/"


[[docs]]
  name = "Developer's Guide"
  weight = 40
  identifier = "developers-guide"
  url = "/developers-guide/"


[[docs]]
  name = "Operators's Manual"
  weight = 60
  identifier = "operators-manual"
  url = "/operators-manual/"
  post = "break"


# LOW LEVEL ITEMS

[[docs]]
  name = "Field References"
  weight = 80
  identifier = "fields"
  url = "/fields/"

[[docs]]
  name = "Troubleshooting"
  weight = 80
  identifier = "troubleshooting"
  url = "/troubleshooting/"

[[docs]]
  name = "Contribute"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"


######## QUICKLINKS

  [[quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/tags/fundamentals/"



######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

  [[global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"

  [[global]]
    name = "Docs"
    weight = 5
    identifier = "docs"
    url = "/docs/"

  [[global]]
    name = "Showcase"
    weight = 20
    identifier = "showcase"
    url = "/showcase/"

  [[global]]
    name = "Blog"
    weight = 21
    identifier = "blog"
    url = "/blog/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "Community"
    weight = 150
    icon = true
    identifier = "community"
    post = "external"
    url =  "https://github.com/CARV-ICS-FORTH/frisbee/discussions"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/CARV-ICS-FORTH/frisbee"
