[[docs]]
  name = "About Frisbee"
  weight = 1
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "Getting Started"
  weight = 5
  identifier = "getting-started"
  url = "/getting-started"
  post = "break"


# Core Menus


[[docs]]
  name = "Chart Guide"
  weight = 20
  identifier = "chart-guide"
  post = "expanded"
  url = "/chart-guide/"


[[docs]]
  name = "CLI"
  weight = 40
  post = "break"
  identifier = "commands"
  url = "/commands/"


# LOW LEVEL ITEMS


[[docs]]
  name = "Troubleshooting"
  weight = 60
  identifier = "troubleshooting"
  url = "/troubleshooting/"


[[docs]]
  name = "Hosting & Deployment"
  weight = 80
  identifier = "hosting-and-deployment"
  url = "/hosting-and-deployment/"

[[docs]]
  name = "Contribute"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/contribute/"


######## QUICKLINKS

  [[quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/tags/fundamentals/"




######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "News"
    weight = 1
    identifier = "news"
    url = "/news/"

  [[global]]
    name = "Docs"
    weight = 5
    identifier = "docs"
    url = "/documentation/"

    [[global]]
      name = "Showcase"
      weight = 20
      identifier = "showcase"
      url = "/showcase/"

  # Anything with a weight > 100 gets an external icon
  [[global]]
    name = "Community"
    weight = 150
    icon = true
    identifier = "community"
    post = "external"
    url =  "https://github.com/CARV-ICS-FORTH/frisbee/discussions"


  [[global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/CARV-ICS-FORTH/frisbee"